# Generated by Django 5.0.2 on 2024-02-29 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_board_boards_board_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.board'),
        ),
    ]
