# Generated by Django 5.0.2 on 2024-02-29 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_board_task_column_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='boards',
            field=models.ManyToManyField(related_name='users_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
