# Generated by Django 5.0.2 on 2024-03-07 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtask_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
